---
plugin: aws_ec2
# Populate inventory with instances in these regions
regions:
  - ap-southeast-2
filters:
  tag:Project: Public_UAT
keyed_groups:
  - prefix: tag
    key: tags['Name']
become: yes
become_user: root
# boto_profile: default
env:
  AWS_ACCESS_KEY: 
    - "{{aws_access_key}}"
  AWS_SECRET_KEY: 
    - "{{aws_secret_key}}"
