FROM mongo:latest

ARG MONGO_ENV=development
ENV MONGO_ENV=${MONGO_ENV}
# ENV MONGO_INITDB_ROOT_USERNAME: root
# ENV MONGO_INITDB_ROOT_PASSWORD: secret
# ENV MONGO_INITDB_DATABASE: users
# WORKDIR ./
# COPY . .

EXPOSE 27017:27017

# RUN "sudo mongod -dbpath=/data/db"
# CMD [ "mongo" "start" ]